src/Entity/Account.php
<?php

namespace App\Entity;

use App\Repository\AccountRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: AccountRepository::class)]
class Account implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }
}

src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AddressRepository::class)]
class Address
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $road = null;

    #[ORM\Column]
    private ?int $house_number = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $postal_code = null;

    #[ORM\Column(length: 255)]
    private ?string $country = null;

    #[ORM\Column]
    private ?bool $is_legal = null;

    #[ORM\ManyToOne(inversedBy: 'address', cascade: ['persist', 'remove'])]
    private ?Company $company = null;

    #[ORM\OneToOne(mappedBy: 'address', cascade: ['persist', 'remove'])]
    private ?Site $site = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRoad(): ?string
    {
        return $this->road;
    }

    public function setRoad(string $road): self
    {
        $this->road = $road;

        return $this;
    }

    public function getHouseNumber(): ?int
    {
        return $this->house_number;
    }

    public function setHouseNumber(int $house_number): self
    {
        $this->house_number = $house_number;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function isIsLegal(): ?bool
    {
        return $this->is_legal;
    }

    public function setIsLegal(bool $is_legal): self
    {
        $this->is_legal = $is_legal;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(Site $site): self
    {
        // set the owning side of the relation if necessary
        if ($site->getAddress() !== $this) {
            $site->setAddress($this);
        }

        $this->site = $site;

        return $this;
    }
}

src/Entity/Site.php
<?php

namespace App\Entity;

use App\Entity\Address;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\SiteRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: SiteRepository::class)]
class Site
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $legal_name = null;

    #[ORM\ManyToOne(inversedBy: 'sites')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Company $company = null;

    #[ORM\ManyToOne(inversedBy: 'site')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Operator $supervisor = null;

    #[ORM\OneToOne(inversedBy: 'site', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?address $address = null;

    #[ORM\OneToMany(mappedBy: 'site', targetEntity: Plant::class, orphanRemoval: true)]
    private Collection $plant;

    public function __construct()
    {
        $this->plant = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLegalName(): ?string
    {
        return $this->legal_name;
    }

    public function setLegalName(string $legal_name): self
    {
        $this->legal_name = $legal_name;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getSupervisor(): ?Operator
    {
        return $this->supervisor;
    }

    public function setSupervisor(?Operator $supervisor): self
    {
        $this->supervisor = $supervisor;

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(Address $address): self
    {
        $this->address = $address;

        return $this;
    }

    /**
     * @return Collection<int, Plant>
     */
    public function getPlant(): Collection
    {
        return $this->plant;
    }

    public function addPlant(Plant $plant): self
    {
        if (!$this->plant->contains($plant)) {
            $this->plant->add($plant);
            $plant->setSite($this);
        }

        return $this;
    }

    public function removePlant(Plant $plant): self
    {
        if ($this->plant->removeElement($plant)) {
            // set the owning side to null (unless already changed)
            if ($plant->getSite() === $this) {
                $plant->setSite(null);
            }
        }

        return $this;
    }
}

src/Form/SiteType.php
<?php

namespace App\Form;

use App\Entity\Site;
use App\Entity\Company;
use App\Entity\Operator;
use App\Form\AddressType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('legal_name')
            ->add('company', EntityType::class, [
                'class'=>Company::class,
                'choice_label'=>'legal_name'
                
            ])
            ->add('supervisor', EntityType::class, [
                'class'=>Operator::class,
                'choice_label'=> function($operator) {
                    return $operator->getId() . ' ' . $operator->getName() . ' ' . $operator->getLastName();
                }
            ])
            ->add('address', AddressType::class);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Site::class,
        ]);
    }
}

src/Controller/SiteController.php
<?php

namespace App\Controller;

use App\Entity\Site;
use App\Form\SiteType;
use App\Repository\SiteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/site')]
class SiteController extends AbstractController
{
    #[Route('/', name: 'app_site_index', methods: ['GET'])]
    public function index(SiteRepository $siteRepository): Response
    {
        return $this->render('site/index.html.twig', [
            'sites' => $siteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_site_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SiteRepository $siteRepository): Response
    {
        $site = new Site();
        $form = $this->createForm(SiteType::class, $site);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $siteRepository->save($site, true);
            return $this->redirectToRoute('app_site_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('site/new.html.twig', [
            'site' => $site,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_site_show', methods: ['GET'])]
    public function show(Site $site): Response
    {
        return $this->render('site/show.html.twig', [
            'site' => $site,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_site_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Site $site, SiteRepository $siteRepository): Response
    {
        $form = $this->createForm(SiteType::class, $site);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $siteRepository->save($site, true);

            return $this->redirectToRoute('app_site_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('site/edit.html.twig', [
            'site' => $site,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_site_delete', methods: ['POST'])]
    public function delete(Request $request, Site $site, SiteRepository $siteRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$site->getId(), $request->request->get('_token'))) {
            $siteRepository->remove($site, true);
        }

        return $this->redirectToRoute('app_site_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/site/_delete_form.html.twig
<form method="post" action="{{ path('app_site_delete', {'id': site.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ site.id) }}">
    <button class="btn">Delete</button>
</form>

templates/site/_form.html.twig
{{ form_start(form) }}
    <div>{{ form_errors(form)}}</div>

    <div>
        {{ form_label(form.legal_name, 'Enter the legal name', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.legal_name, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.legal_name)}}
    </div>

    <div>
        {{ form_label(form.company, 'Enter the company', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.company, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.company)}}
    </div>
    <h2>
        {{ form_label(form.address, 'address', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
    </h2>
    <div>
        {{ form_label(form.address.road, 'Enter the road', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.address.road, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.address.road)}}
    </div>

    <div>
        {{ form_label(form.address.house_number, 'Enter the house number', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.address.house_number, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.address.house_number)}}
    </div>

    <div>
        {{ form_label(form.address.city, 'Enter the city', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.address.city, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.address.city)}}
    </div>

    <div>
        {{ form_label(form.address.postal_code, 'Enter the postal code', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.address.postal_code, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.address.postal_code)}}
    </div>

    <div>
        {{ form_label(form.address.country, 'Enter the country', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.address.country, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.address.country)}}
    </div>

    <div class="flex items-center mt-4 mb-4">
        {{ form_label(form.address.is_legal, 'Is Legal', {'label_attr': {'class': 'text-sm text-gray-700 dark:text-gray-300 font-medium mr-2'}}) }}
        {{ form_widget(form.address.is_legal, {'attr': {'class': 'h-4 w-4 rounded border-gray border text-indigo-300 '}}) }}
    </div>

    <div>
        {{ form_label(form.supervisor, 'Enter the supervisor', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.supervisor, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.supervisor)}}
    </div>




    <button type="submit" class="w-full shadow-sm border-transparent bg-indigo-600 hover:bg-indigo-700 dark:bg-indigo-500 dark:bg-indigo-400 text-white rounded-md border p2 mb-2 mt-4">Save</button>
{{ form_end(form)}}

templates/site/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Site{% endblock %}

{% block body %}
    <h1>Edit Site</h1>

    {{ include('site/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_site_index') }}">back to list</a>

    {{ include('site/_delete_form.html.twig') }}
{% endblock %}

templates/site/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Site index{% endblock %}

{% block body %}
    <h1>Site index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Legal_name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for site in sites %}
            <tr>
                <td>{{ site.id }}</td>
                <td>{{ site.legalName }}</td>
                <td>
                    <a href="{{ path('app_site_show', {'id': site.id}) }}">show</a>
                    <a href="{{ path('app_site_edit', {'id': site.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_site_new') }}">Create new</a>
{% endblock %}

templates/site/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Site{% endblock %}

{% block body %}
    <h1>Create new Site</h1>

    {{ include('site/_form.html.twig') }}

    <a href="{{ path('app_site_index') }}">back to list</a>
{% endblock %}

templates/site/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ site.legalName }}{% endblock %}

{% block bread %}{{ site.legalName }}{% endblock %}

{% block body %}
    <div class="border-t border-gray-200 px-4 py-5 sm:p-0 dark:border-neutral-500 dark:bg-neutral-600">
        <dl class="sm:divide-y sm:divide-gray-200">
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500 dark:text-white">
                    Id
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-white">
                    {{ site.id }}
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 ">
                <dt class="text-sm font-medium text-gray-500 dark:text-white">
                    Legal Name
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-white">
                    {{ site.legalName }}
                </dd>
            </div>
             <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 ">
                <dt class="text-sm font-medium text-gray-500 dark:text-white">
                    Company
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-white">
                    {{ site.company.legalName }}
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 ">
                <dt class="text-sm font-medium text-gray-500 dark:text-white">
                    Address
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-white">
                    {{ site.address.road}}, {{ site.address.houseNumber}}, {{ site.address.city}}
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 ">
                <dt class="text-sm font-medium text-gray-500 dark:text-white">
                    Supervisor
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-white">
                    {{ site.supervisor.id}}, {{ site.supervisor.name}} {{ site.supervisor.lastName}}
                </dd>
            </div>
            
        </dl>
    </div>
    <a class="text-blue-500" href="{{ path('app_site_index') }}">Back</a>
    <br>
    <a class="text-blue-500" href="{{ path('app_site_edit', {'id': site.id}) }}">Edit</a>

    {{ include('site/_delete_form.html.twig') }}
{% endblock %}