src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AddressRepository::class)]
class Address
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $road = null;

    #[ORM\Column]
    private ?int $house_number = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $postal_code = null;

    #[ORM\Column(length: 255)]
    private ?string $country = null;

    #[ORM\Column]
    private ?bool $is_legal = null;

    #[ORM\ManyToOne(inversedBy: 'address', cascade: ['persist', 'remove'])]
    private ?Company $company = null;

    #[ORM\OneToOne(mappedBy: 'address', cascade: ['persist', 'remove'])]
    private ?Site $site = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRoad(): ?string
    {
        return $this->road;
    }

    public function setRoad(string $road): self
    {
        $this->road = $road;

        return $this;
    }

    public function getHouseNumber(): ?int
    {
        return $this->house_number;
    }

    public function setHouseNumber(int $house_number): self
    {
        $this->house_number = $house_number;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function isIsLegal(): ?bool
    {
        return $this->is_legal;
    }

    public function setIsLegal(bool $is_legal): self
    {
        $this->is_legal = $is_legal;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(Site $site): self
    {
        // set the owning side of the relation if necessary
        if ($site->getAddress() !== $this) {
            $site->setAddress($this);
        }

        $this->site = $site;

        return $this;
    }
}

src/Entity/Company.php
<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CompanyRepository::class)]
class Company
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $legal_name = null;

    #[ORM\Column(length: 255)]
    private ?string $vat_number = null;

    #[ORM\OneToMany(mappedBy: 'company', targetEntity: Site::class, orphanRemoval: true)]
    private Collection $sites;

    #[ORM\OneToMany(mappedBy: 'company', targetEntity: Contact::class, cascade: ['persist', 'remove'])]
    private Collection $contact;

    #[ORM\OneToMany(mappedBy: 'company', targetEntity: Address::class, cascade: ['persist', 'remove'])]
    private Collection $address;

    public function __construct()
    {
        $this->sites = new ArrayCollection();
        $this->contact = new ArrayCollection();
        $this->address = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLegalName(): ?string
    {
        return $this->legal_name;
    }

    public function setLegalName(string $legal_name): self
    {
        $this->legal_name = $legal_name;

        return $this;
    }

    public function getVatNumber(): ?string
    {
        return $this->vat_number;
    }

    public function setVatNumber(string $vat_number): self
    {
        $this->vat_number = $vat_number;

        return $this;
    }

    /**
     * @return Collection<int, site>
     */
    public function getSites(): Collection
    {
        return $this->sites;
    }

    public function addSite(site $site): self
    {
        if (!$this->sites->contains($site)) {
            $this->sites->add($site);
            $site->setCompany($this);
        }

        return $this;
    }

    public function removeSite(site $site): self
    {
        if ($this->sites->removeElement($site)) {
            // set the owning side to null (unless already changed)
            if ($site->getCompany() === $this) {
                $site->setCompany(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Contact>
     */
    public function getContact(): Collection
    {
        return $this->contact;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contact->contains($contact)) {
            $this->contact->add($contact);
            $contact->setCompany($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contact->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getCompany() === $this) {
                $contact->setCompany(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, address>
     */
    public function getAddress(): Collection
    {
        return $this->address;
    }

    public function addAddress(address $address): self
    {
        if (!$this->address->contains($address)) {
            $this->address->add($address);
            $address->setCompany($this);
        }

        return $this;
    }

    public function removeAddress(address $address): self
    {
        if ($this->address->removeElement($address)) {
            // set the owning side to null (unless already changed)
            if ($address->getCompany() === $this) {
                $address->setCompany(null);
            }
        }

        return $this;
    }
}

src/Form/CompanyType.php
<?php

namespace App\Form;

use App\Entity\Company;
use App\Form\AddressType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CompanyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('legal_name')
            ->add('vat_number')
            ->add('address', CollectionType::class, [
                'entry_type'=>addressType::class,
                'entry_options'=>[],
                'allow_add'=>true,
                'label'=>false
            ])
            ->add('contact', CollectionType::class, [
                'entry_type'=>ContactType::class,
                'entry_options'=>[],
                'allow_add'=>true,
                'label'=>false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Company::class,
        ]);
    }
}

src/Controller/CompanyController.php
<?php

namespace App\Controller;

use App\Entity\Company;
use App\Form\CompanyType;
use App\Repository\CompanyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/company')]
class CompanyController extends AbstractController
{
    #[Route('/', name: 'app_company_index', methods: ['GET'])]
    public function index(CompanyRepository $companyRepository): Response
    {
        return $this->render('company/index.html.twig', [
            'companies' => $companyRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_company_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CompanyRepository $companyRepository): Response
    {
        $company = new Company();
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $companyRepository->save($company, true);

            return $this->redirectToRoute('app_company_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('company/new.html.twig', [
            'company' => $company,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_company_show', methods: ['GET'])]
    public function show(Company $company): Response
    {
        return $this->render('company/show.html.twig', [
            'company' => $company,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_company_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Company $company, CompanyRepository $companyRepository): Response
    {
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $companyRepository->save($company, true);

            return $this->redirectToRoute('app_company_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('company/edit.html.twig', [
            'company' => $company,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_company_delete', methods: ['POST'])]
    public function delete(Request $request, Company $company, CompanyRepository $companyRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$company->getId(), $request->request->get('_token'))) {
            $companyRepository->remove($company, true);
        }

        return $this->redirectToRoute('app_company_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/company/_delete_form.html.twig
<form method="post" action="{{ path('app_company_delete', {'id': company.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ company.id) }}">
    <button class="btn">Delete</button>
</form>

templates/company/_form.html.twig
{{ form_start(form) }}
    <div>{{ form_errors(form)}}</div>

    <div>
        {{ form_label(form.legal_name, 'Enter the legal name', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.legal_name, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.legal_name)}}
    </div>

    <div>
        {{ form_label(form.vat_number, 'Enter the vat number', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.vat_number, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.vat_number)}}
    </div>
    <ul class="address"
        data-index="{{ form.address|length > 0 ? form.address|last.vars.name + 1 : 0 }}"
        data-prototype="{{ form_widget(form.address.vars.prototype)|e('html_attr') }}"
    ></ul>
    <button type="button" class="add_item_link" data-collection-holder-class="address">Add a address</button>
    <ul class="contact"
        data-index="{{ form.contact|length > 0 ? form.contact|last.vars.name + 1 : 0 }}"
        data-prototype="{{ form_widget(form.contact.vars.prototype)|e('html_attr') }}"
    ></ul>
    <button type="button" class="add_item_link" data-collection-holder-class="contact">Add a contact</button>
    <script>
        const addFormToCollection = (e) => {
            const collectionHolder = document.querySelector('.' + e.currentTarget.dataset.collectionHolderClass);

            const item = document.createElement('li');

            item.innerHTML = collectionHolder
                .dataset
                .prototype
                .replace(
                /__name__/g,
                collectionHolder.dataset.index
                );

            collectionHolder.appendChild(item);

            collectionHolder.dataset.index++;
        };
        document
            .querySelectorAll('.add_item_link')
            .forEach(btn => {
                btn.addEventListener("click", addFormToCollection)
            });
    </script>
    {% for address in form.address %}
        <h2>
            {{ form_label(address, 'address', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        </h2>
        <div>
            {{ form_label(address.road, 'Enter the road', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
            {{ form_widget(address.road, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
            {{ form_errors(address.road)}}
        </div>

        <div>
            {{ form_label(address.house_number, 'Enter the house number', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
            {{ form_widget(address.house_number, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
            {{ form_errors(address.house_number)}}
        </div>

        <div>
            {{ form_label(address.city, 'Enter the city', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
            {{ form_widget(address.city, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
            {{ form_errors(address.city)}}
        </div>

        <div>
            {{ form_label(address.postal_code, 'Enter the postal code', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
            {{ form_widget(address.postal_code, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
            {{ form_errors(address.postal_code)}}
        </div>

        <div>
            {{ form_label(address.country, 'Enter the country', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
            {{ form_widget(address.country, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
            {{ form_errors(address.country)}}
        </div>

        <div class="flex items-center mt-4 mb-4">
            {{ form_label(address.is_legal, 'Is Legal', {'label_attr': {'class': 'text-sm text-gray-700 dark:text-gray-300 font-medium mr-2'}}) }}
            {{ form_widget(address.is_legal, {'attr': {'class': 'h-4 w-4 rounded border-gray border text-indigo-300 '}}) }}
        </div>
    {% endfor %}

    {% for contact in form.contact %}
        <h2>
            {{ form_label(contact, 'contact', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        </h2>
        <div>
            {{ form_label(contact.email, 'Enter the email', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
            {{ form_widget(contact.email, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
            {{ form_errors(contact.email)}}
        </div>

        <div>
            {{ form_label(contact.phone_number, 'Enter the phone number', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
            {{ form_widget(contact.phone_number, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
            {{ form_errors(contact.phone_number)}}
        </div>

        <div>
            {{ form_label(contact.name, 'Enter your name', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
            {{ form_widget(contact.name, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
            {{ form_errors(contact.name)}}
        </div>

        <div>
            {{ form_label(contact.last_name, 'Enter your last name', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
            {{ form_widget(contact.last_name, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
            {{ form_errors(contact.last_name)}}
        </div>

        <div class="flex items-center mt-4 mb-4">
            {{ form_label(contact.is_main, 'Is main', {'label_attr': {'class': 'text-sm text-gray-700 dark:text-gray-300 font-medium mr-2'}}) }}
            {{ form_widget(contact.is_main, {'attr': {'class': 'h-4 w-4 rounded border-gray border text-indigo-300 '}}) }}
        </div>
    {% endfor %}



    <button type="submit" class="w-full shadow-sm border-transparent bg-indigo-600 hover:bg-indigo-700 dark:bg-indigo-500 dark:bg-indigo-400 text-white rounded-md border p2 mb-2 mt-4">Save</button>
{{ form_end(form)}}

templates/company/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Company{% endblock %}

{% block bread %}Edit Company{% endblock %}
{% block body %}

    {{ include('company/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_company_index') }}">back to list</a>

    {{ include('company/_delete_form.html.twig') }}
{% endblock %}

templates/company/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Company table{% endblock %}

{% block bread %}Company index{% endblock %}

{% block body %}
    <div class="flex flex-col">
        <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                    <table class="min-w-full text-left text-sm font-light">
                    <thead
                    class="border-b bg-neutral-200 font-medium dark:border-neutral-500 dark:bg-neutral-600">
                    <tr>
                        <th scope="col" class="px-6 py-4">Id</th>
                        <th scope="col" class="px-6 py-4">Legal_name</th>
                        <th scope="col" class="px-6 py-4">Vat_number</th>
                        <th scope="col" class="px-6 py-4">Addresses</th>
                        <th scope="col" class="px-6 py-4">actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for company in companies %}
                        <tr
                        class="border-b bg-neutral-100 dark:border-neutral-500 dark:bg-neutral-700">
                            <td class="whitespace-nowrap px-6 py-4">{{ company.id }}</td>
                            <td class="whitespace-nowrap px-6 py-4">{{ company.legalName }}</td>
                            <td class="whitespace-nowrap px-6 py-4">{{ company.vatNumber }}</td>
                            <td class="whitespace-nowrap px-6 py-4">
                                <ul>
                                    {% for address in company.address %}
                                        <li>
                                            {{ address.road }}, {{ address.houseNumber }}
                                        </li>
                                    {% endfor %}
                                </ul>
                            </td>
                            <td>
                                <a class="whitespace-nowrap px-6 py-4" href="{{ path('app_company_show', {'id': company.id}) }}">show</a>
                                <a href="{{ path('app_company_edit', {'id': company.id}) }}">edit</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="4">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <a class="text-blue-500" href="{{ path('app_company_new') }}">Create new</a>
{% endblock %}

templates/company/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Company{% endblock %}
{% block bread %}Create new Company{% endblock %}

{% block body %}

    {{ include('company/_form.html.twig') }}

    <a class="text-blue-500" href="{{ path('app_company_index') }}">back to list</a>
{% endblock %}

templates/company/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ company.legalName }}{% endblock %}

{% block bread %}{{ company.legalName }}{% endblock %}

{% block body %}
    <div class="border-t border-gray-200 px-4 py-5 sm:p-0 dark:border-neutral-500 dark:bg-neutral-600">
        <dl class="sm:divide-y sm:divide-gray-200">
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500 dark:text-white">
                    Id
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-white">
                    {{ company.id }}
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 ">
                <dt class="text-sm font-medium text-gray-500 dark:text-white">
                    Legal Name
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-white">
                    {{ company.legalName }}
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 ">
                <dt class="text-sm font-medium text-gray-500 dark:text-white">
                    Vat Number
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-white">
                    {{ company.vatNumber}}
                </dd>
            </div>
            
        </dl>
    </div>
    <a class="text-blue-500" href="{{ path('app_company_index') }}">Back</a>
    <br>
    <a class="text-blue-500" href="{{ path('app_company_edit', {'id': company.id}) }}">Edit</a>

    {{ include('company/_delete_form.html.twig') }}
{% endblock %}