src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AddressRepository::class)]
class Address
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $road = null;

    #[ORM\Column]
    private ?int $house_number = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $postal_code = null;

    #[ORM\Column(length: 255)]
    private ?string $country = null;

    #[ORM\Column]
    private ?bool $is_legal = null;

    #[ORM\ManyToOne(inversedBy: 'address', cascade: ['persist', 'remove'])]
    private ?Company $company = null;

    #[ORM\OneToOne(mappedBy: 'address', cascade: ['persist', 'remove'])]
    private ?Site $site = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRoad(): ?string
    {
        return $this->road;
    }

    public function setRoad(string $road): self
    {
        $this->road = $road;

        return $this;
    }

    public function getHouseNumber(): ?int
    {
        return $this->house_number;
    }

    public function setHouseNumber(int $house_number): self
    {
        $this->house_number = $house_number;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function isIsLegal(): ?bool
    {
        return $this->is_legal;
    }

    public function setIsLegal(bool $is_legal): self
    {
        $this->is_legal = $is_legal;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(Site $site): self
    {
        // set the owning side of the relation if necessary
        if ($site->getAddress() !== $this) {
            $site->setAddress($this);
        }

        $this->site = $site;

        return $this;
    }
}

src/Form/AddressType.php
<?php

namespace App\Form;

use App\Entity\Address;
use App\Entity\Company;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

class AddressType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('road', TextType::class, array(
                'attr'=>['class'=>'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'],
                'label'=>'Road',
                'label_attr'=>['class'=>'block text-sm text-grey-700 dark:text-grey-300 font-medium'],
                'required'=>true
            ))
            ->add('house_number', IntegerType::class, array(
                'attr'=>['class'=>'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'],
                'label'=>'House number',
                'label_attr'=>['class'=>'block text-sm text-grey-700 dark:text-grey-300 font-medium'],
                'required'=>true
            ))
            ->add('city', TextType::class, array(
                'attr'=>['class'=>'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'],
                'label'=>'City',
                'label_attr'=>['class'=>'block text-sm text-grey-700 dark:text-grey-300 font-medium'],
                'required'=>true
            ))
            ->add('postal_code', TextType::class, array(
                'attr'=>['class'=>'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'],
                'label'=>'Postal code',
                'label_attr'=>['class'=>'block text-sm text-grey-700 dark:text-grey-300 font-medium'],
                'required'=>true
            ))
            ->add('country', TextType::class, array(
                'attr'=>['class'=>'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'],
                'label'=>'Country',
                'label_attr'=>['class'=>'block text-sm text-grey-700 dark:text-grey-300 font-medium'],
                'required'=>true
            ))
            ->add('is_legal', CheckboxType::class, array(
                'attr'=>['class'=>'h-4 w-4 rounded border-gray border text-indigo-300'],
                'label'=>'Is legal',
                'label_attr'=>['class'=>'text-sm text-grey-700 dark:text-grey-300 font-medium mr-2']
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Address::class,
        ]);
    }
}

src/Controller/AddressController.php
<?php

namespace App\Controller;

use App\Entity\Address;
use App\Form\AddressType;
use App\Repository\AddressRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/address')]
class AddressController extends AbstractController
{
    #[Route('/', name: 'app_address_index', methods: ['GET'])]
    public function index(AddressRepository $addressRepository): Response
    {
        return $this->render('address/index.html.twig', [
            'addresses' => $addressRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_address_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AddressRepository $addressRepository): Response
    {
        $address = new Address();
        $form = $this->createForm(AddressType::class, $address);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $addressRepository->save($address, true);

            return $this->redirectToRoute('app_address_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('address/new.html.twig', [
            'address' => $address,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_address_show', methods: ['GET'])]
    public function show(Address $address): Response
    {
        return $this->render('address/show.html.twig', [
            'address' => $address,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_address_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Address $address, AddressRepository $addressRepository): Response
    {
        $form = $this->createForm(AddressType::class, $address);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $addressRepository->save($address, true);

            return $this->redirectToRoute('app_address_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('address/edit.html.twig', [
            'address' => $address,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_address_delete', methods: ['POST'])]
    public function delete(Request $request, Address $address, AddressRepository $addressRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$address->getId(), $request->request->get('_token'))) {
            $addressRepository->remove($address, true);
        }

        return $this->redirectToRoute('app_address_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/address/_delete_form.html.twig
<form method="post" action="{{ path('app_address_delete', {'id': address.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ address.id) }}">
    <button class="btn">Delete</button>
</form>

templates/address/_form.html.twig
{{ form_start(form) }}
    <div>{{ form_errors(form)}}</div>

    <div>
        {{ form_label(form.road, 'Enter the road', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.road, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.road)}}
    </div>

    <div>
        {{ form_label(form.house_number, 'Enter the house number', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.house_number, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.house_number)}}
    </div>

    <div>
        {{ form_label(form.city, 'Enter the city', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.city, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.city)}}
    </div>

    <div>
        {{ form_label(form.postal_code, 'Enter the postal code', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.postal_code, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.postal_code)}}
    </div>

    <div>
        {{ form_label(form.country, 'Enter the country', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.country, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.country)}}
    </div>

    <div>
        {{ form_label(form.company, 'Enter the company', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.company, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.company)}}
    </div>

    <div>
        {{ form_label(form.site, 'Enter the site', {'label_attr':{'class':'block text-sm text-grey-700 dark:text-grey-300 font-medium'}})}}
        {{ form_widget(form.site, {'attr':{'class':'block w-full shadow-sm border-gray-300 dark:border-transparent dark:text-gray-800 rounded-md border p2 mt-1 bm-2'}})}}
        {{ form_errors(form.site)}}
    </div>

    <div class="flex items-center mt-4 mb-4">
        {{ form_label(form.is_legal, 'Is Legal', {'label_attr': {'class': 'text-sm text-gray-700 dark:text-gray-300 font-medium mr-2'}}) }}
        {{ form_widget(form.is_legal, {'attr': {'class': 'h-4 w-4 rounded border-gray border text-indigo-300 '}}) }}
    </div>




    <button type="submit" class="w-full shadow-sm border-transparent bg-indigo-600 hover:bg-indigo-700 dark:bg-indigo-500 dark:bg-indigo-400 text-white rounded-md border p2 mb-2 mt-4">Save</button>
{{ form_end(form)}}

templates/address/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Address{% endblock %}

{% block body %}
    <h1>Edit Address</h1>

    {{ include('address/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_address_index') }}">back to list</a>

    {{ include('address/_delete_form.html.twig') }}
{% endblock %}

templates/address/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Address index{% endblock %}

{% block body %}
    <h1>Address index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Road</th>
                <th>House_number</th>
                <th>City</th>
                <th>Postal_code</th>
                <th>Country</th>
                <th>Is_legal</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for address in addresses %}
            <tr>
                <td>{{ address.id }}</td>
                <td>{{ address.road }}</td>
                <td>{{ address.houseNumber }}</td>
                <td>{{ address.city }}</td>
                <td>{{ address.postalCode }}</td>
                <td>{{ address.country }}</td>
                <td>{{ address.isLegal ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_address_show', {'id': address.id}) }}">show</a>
                    <a href="{{ path('app_address_edit', {'id': address.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_address_new') }}">Create new</a>
{% endblock %}

templates/address/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Address{% endblock %}

{% block body %}
    <h1>Create new Address</h1>

    {{ include('address/_form.html.twig') }}

    <a href="{{ path('app_address_index') }}">back to list</a>
{% endblock %}

templates/address/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Address{% endblock %}

{% block body %}
    <h1>Address</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ address.id }}</td>
            </tr>
            <tr>
                <th>Road</th>
                <td>{{ address.road }}</td>
            </tr>
            <tr>
                <th>House_number</th>
                <td>{{ address.houseNumber }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ address.city }}</td>
            </tr>
            <tr>
                <th>Postal_code</th>
                <td>{{ address.postalCode }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ address.country }}</td>
            </tr>
            <tr>
                <th>Is_legal</th>
                <td>{{ address.isLegal ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_address_index') }}">back to list</a>

    <a href="{{ path('app_address_edit', {'id': address.id}) }}">edit</a>

    {{ include('address/_delete_form.html.twig') }}
{% endblock %}